# Generated by Django 4.2.20 on 2025-05-09 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('primary_color', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('rtl_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('trial', 'trial'), ('suspended', 'suspended'), ('cancelled', 'cancelled'), ('pending', 'pending')], max_length=100)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('company_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpms.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_owner', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='zoneownerbankaccount',
            name='account_type',
            field=models.CharField(choices=[('bank_account', 'bank_account'), ('wallet', 'wallet'), ('other', 'other')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='parkingfloor',
            unique_together={('zone', 'floor_number')},
        ),
        migrations.AlterUniqueTogether(
            name='parkingzone',
            unique_together={('zone_owner', 'name')},
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpms.owner'),
        ),
    ]
