# Generated by Django 4.2.20 on 2025-05-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0002_owner_staff_remove_parkingslot_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together={('company_owner', 'company_name')},
        ),
    ]
