# Generated by Django 4.2.20 on 2025-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0003_alter_owner_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('terminated', 'terminated')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('owner',)},
        ),
    ]
