# Generated by Django 4.2.20 on 2025-05-09 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0004_alter_subscription_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zoneownerbankaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='zoneownerbankaccount',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpms.owner'),
        ),
        migrations.AlterUniqueTogether(
            name='zoneownerbankaccount',
            unique_together={('owner',)},
        ),
        migrations.RemoveField(
            model_name='zoneownerbankaccount',
            name='user',
        ),
    ]
