# Generated by Django 5.1.7 on 2025-05-12 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0007_emailresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlotGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('Parking_floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpms.parkingfloor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='parking_slot_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpms.parkingslotgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingslot',
            unique_together={('parking_slot_group', 'slot_number')},
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='parking_floor',
        ),
    ]
