# Generated by Django 5.1.7 on 2025-05-15 09:19

import django.db.models.deletion
import vpms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0008_parkingslotgroup_alter_parkingslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpms.vehicletype'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pricingrule',
            unique_together={('parking_zone', 'vehicle_type', 'start_time', 'end_time', 'day_of_week')},
        ),
        migrations.CreateModel(
            name='ParkingZonePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=vpms.models.get_parking_zone_image_upload_path, validators=[vpms.models.validate_parking_zone_picture])),
                ('parking_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpms.parkingzone')),
            ],
        ),
    ]
