# Generated by Django 5.1.7 on 2025-05-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0009_pricingrule_vehicle_type_alter_pricingrule_rule_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='company_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='company_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='company_phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
