# Generated by Django 4.2.20 on 2025-05-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0011_rename_parking_floor_parkingslotgroup_parking_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
