# Generated by Django 4.2.20 on 2025-05-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0012_alter_pricingrule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT'), ('SUN', 'SUN')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DefaultPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('parking_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpms.parkingzone')),
            ],
            options={
                'unique_together': {('parking_zone',)},
            },
        ),
    ]
