# Generated by Django 5.1.7 on 2025-05-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0013_alter_pricingrule_day_of_week_defaultprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='status',
            field=models.CharField(default='inactive', max_length=100),
        ),
    ]
