# Generated by Django 5.1.7 on 2025-05-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0014_parkingzone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='parking_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpms.parkingzone'),
        ),
        migrations.AlterField(
            model_name='parkingzone',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
