# Generated by Django 5.1.7 on 2025-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0015_staff_parking_zone_alter_parkingzone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
