# Generated by Django 5.1.7 on 2025-05-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0016_booking_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
