# Generated by Django 5.1.7 on 2025-06-05 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0017_alter_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailresetcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
