# Generated by Django 5.1.7 on 2025-06-07 07:57

import django.db.models.deletion
import vpms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0018_alter_emailresetcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpms.parkingzone'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=vpms.models.get_subscription_payment_image_upload_path, validators=[vpms.models.validate_subscription_payment_picture]),
        ),
    ]
