# Generated by Django 5.1.7 on 2025-06-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0019_notification_zone_subscriptionpayment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneutitlities',
            name='drainage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zoneutitlities',
            name='fuel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zoneutitlities',
            name='lighting',
            field=models.BooleanField(default=False),
        ),
    ]
