# Generated by Django 5.1.7 on 2025-06-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0020_zoneutitlities_drainage_zoneutitlities_fuel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZoneUtitlities',
            new_name='ZoneUtilities',
        ),
    ]
