# Generated by Django 5.1.7 on 2025-06-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpms', '0021_rename_zoneutitlities_zoneutilities'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritezones',
            unique_together={('user', 'parking_zone')},
        ),
    ]
